# Setup
title:               zting
tagline:             'A Jekyll theme'
description:         'lets develop with zting'
url:                 https://zting94.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              zting 
  url:               https://zting94.github.io
  email:             kyk0128tt@naver.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
